import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainLayout from "@/components/main_layout";
import SocketProvider from "../contexts/socketContext";
import ControllerProvider from "@/contexts/controllerContext";
import { Toaster } from "@/components/ui/toaster";
import { ToastProvider } from "@/components/ui/toast";
import AuthProvider from "@/contexts/authContext";
import CourseProvider from "@/contexts/courseContext";
import BotProvider from "@/contexts/botContext";
import BotVisitProvider from "@/contexts/botVisitContext";
import RegisteredUsersProvider from "@/contexts/registeredUsersContext";
import TransactionProvider from "@/contexts/transactionContext";
import BotSupportProvider from "@/contexts/botSupportContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const geist = localFont({
  src: "./fonts/woff/IRANSansX-Black.woff",
  variable: "--font-geist",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`min-h-full flex items-center font-sans justify-center overflow-hidden bg-[#CEBEE4] text-black`}
      >
        <ToastProvider>
          <SocketProvider>
            <AuthProvider>
              <CourseProvider>
                <BotProvider>
                  <BotVisitProvider>
                    <RegisteredUsersProvider>
                      <BotSupportProvider>
                        <TransactionProvider>
                          <ControllerProvider>{children}</ControllerProvider>
                          <Toaster />
                        </TransactionProvider>
                      </BotSupportProvider>
                    </RegisteredUsersProvider>
                  </BotVisitProvider>
                </BotProvider>
              </CourseProvider>
            </AuthProvider>
          </SocketProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
